# Generated by Django 2.0.2 on 2020-06-17 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200617_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 2, 18, 35, 116408, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
